# Generated by Django 3.0.8 on 2020-08-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='area_hectares',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='justification',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
